- name: Update APT and Install ZSH for local host
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install ZSH
      apt:
        name: zsh
        state: present

# - hosts: localhost
#   become: true
#   pre_tasks:
#    - name: Update cache
#      apt:
#       update_cache: true
#      tags:
#       - zsh
#       - fzf
#   tasks: 
#   - name: Install zsh
#     apt: name=zsh
#     tags:
#     - zsh
#   - name: Change shell
#     shell: chsh -s `which zsh`
#     tags:
#     - zsh
#   - name: Install oh-my-zsh
#     shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
#     tags:
#     - zsh
#   - name: Install Zsh autosuggestions plugin
#     ansible.builtin.git:
#       repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
#       dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
#     tags:
#     - zsh
#   - name: Update Zshrc
#     shell: sed -i 's/(git/(git zsh-autosuggestions/' ~/.zshrc
#     tags:
#     - zsh
#   - name: Install Vim
#     apt: name=zsh
#     tags:
#     - vim
#   - name: Get FZF
#     ansible.builtin.git:
#       repo: 'https://github.com/junegunn/fzf.git'
#       dest: "~/.fzf/"
#       depth: 1
#     tags:
#     - fzf
#   - name: Install FZF
#     shell: ~/.fzf/install
#     tags:
#       - fzf
